// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAirSGt_eTHuYNT-Y9qqJnM8uhTunNVUAQ',
    appId: '1:481932611837:web:21f4e8c3ca180a120a2e94',
    messagingSenderId: '481932611837',
    projectId: 'famlink-6aebf',
    authDomain: 'famlink-6aebf.firebaseapp.com',
    storageBucket: 'famlink-6aebf.firebasestorage.app',
    measurementId: 'G-N4LD6S23HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDclWSnwRldufIDGJR2YSJ8tdf0TSDURK0',
    appId: '1:481932611837:android:b6751f0303c5bd920a2e94',
    messagingSenderId: '481932611837',
    projectId: 'famlink-6aebf',
    storageBucket: 'famlink-6aebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3h_6PZI93O_WJJbbmyDrXQNU31wh7ODw',
    appId: '1:481932611837:ios:c694c52197c2d83d0a2e94',
    messagingSenderId: '481932611837',
    projectId: 'famlink-6aebf',
    storageBucket: 'famlink-6aebf.firebasestorage.app',
    iosBundleId: 'com.avs.famlink',
  );

}